"""Add body to sending_log

Revision ID: 2326ddfccc49
Revises: 8b6624cb70b9
Create Date: 2026-07-10 14:13:06.768567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2326ddfccc49'
down_revision = '8b6624cb70b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'ai_tone')
    op.drop_column('campaigns', 'ai_product_name')
    op.drop_column('campaigns', 'ai_target_audience')
    op.drop_column('campaigns', 'ai_product_description')
    op.drop_column('campaigns', 'ai_campaign_goal')
    op.drop_column('campaigns', 'ai_enabled')
    op.add_column('sending_logs', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sending_logs', 'body')
    op.add_column('campaigns', sa.Column('ai_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('ai_campaign_goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_product_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_target_audience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
