"""Add ai_enabled to campaigns

Revision ID: 8b6624cb70b9
Revises: 014_campaign_ai_context
Create Date: 2026-07-10 13:38:25.217862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6624cb70b9'
down_revision = '014_campaign_ai_context'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('ai_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'ai_enabled')
    # ### end Alembic commands ###
